[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  name = "admincatalog"
  org = "shiroorg"
  version = "0.1.0"

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"
